CREATE TABLE IF NOT EXISTS public.quotes
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author VARCHAR(125) NOT NULL,
    text TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,  -- Voeg een default waarde toe voor 'likes'
    text_author_hash VARCHAR(255) NOT NULL,
    CONSTRAINT quotes_pkey PRIMARY KEY (id),
    CONSTRAINT uk_quotes_text_author_hash UNIQUE (text_author_hash)
);
