CREATE TABLE IF NOT EXISTS quotes
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author VARCHAR(125) NOT NULL,
    text TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    text_author_hash VARCHAR(255) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    CONSTRAINT quotes_pkey PRIMARY KEY (id),
    CONSTRAINT uk_quotes_text_author_hash UNIQUE (text_author_hash, provider) -- quotes should be added once
);

CREATE TABLE IF NOT EXISTS quote_like
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id VARCHAR(64) NOT NULL,
    quote_id BIGINT NOT NULL,
    liked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quote FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_quote UNIQUE (user_id, quote_id) -- prevent user liking their own quote again
);

CREATE INDEX idx_quote_like_user_id ON quote_like(user_id);
