services:

  nginx:
    build:
      context: ../../
      dockerfile: spa-react-frontend/randomquotes.spa/Dockerfile
      target: frontend-runtime
      args:
        - SPADIR=spa-react-frontend/randomquotes.spa
        - NDIR=nginx
    container_name: nginx_spa
    ports:
      # Map host port 5000 to Nginx container's internal port 80
      - "5000:80"
    restart: unless-stopped
